version: '3'
services:

  dbserver:
    image: postgres
    container_name: dbserver
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
 
volumes:
  db_data:
    external: true